# Generated by Django 2.1.7 on 2020-01-13 16:51

import App.models
import ckeditor_uploader.fields
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용')),
                ('is_top', models.BooleanField(default=False, verbose_name='상단고정여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '   게시글',
                'verbose_name_plural': '   게시글',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='업종명')),
            ],
            options={
                'verbose_name': '  업종',
                'verbose_name_plural': '  업종',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='업체명')),
                ('thumbnail', models.ImageField(upload_to=App.models.partner_update_filename, verbose_name='썸네일')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='주소')),
                ('career', models.IntegerField(default=0, verbose_name='경력')),
                ('products', models.TextField(blank=True, verbose_name='진행한 제품')),
                ('special', models.TextField(blank=True, verbose_name='특화분야')),
                ('info', models.TextField(blank=True, verbose_name='회사소개')),
                ('history', models.TextField(blank=True, verbose_name='주요이력')),
                ('is_main', models.BooleanField(default=False, verbose_name='메인노출여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('industry', models.ManyToManyField(to='App.Industry', verbose_name='업종')),
            ],
            options={
                'verbose_name': '  파트너',
                'verbose_name_plural': '  파트너',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=App.models.portfolio_update_filename, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '     포트폴리오',
                'verbose_name_plural': '     포트폴리오',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='제목')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '   프로젝트',
                'verbose_name_plural': '   프로젝트',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(default=App.models.get_default_hash_id, max_length=50, verbose_name='유저명')),
                ('manager', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('manager_position', models.CharField(blank=True, max_length=50, verbose_name='담당자 직급')),
                ('manager_department', models.CharField(blank=True, max_length=50, verbose_name='담당자 부서명')),
                ('business_name', models.CharField(blank=True, max_length=50, verbose_name='사업자명')),
                ('business_number', models.CharField(blank=True, max_length=50, verbose_name='사업자번호')),
                ('business_license', models.FileField(blank=True, upload_to=App.models.business_license_update_filename, verbose_name='사업자등록증')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='휴대폰 번호')),
                ('tel', models.CharField(blank=True, max_length=200, verbose_name='유선 번호')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '      회원',
                'verbose_name_plural': '      회원',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
