# Generated by Django 2.1.7 on 2020-01-14 15:54

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_project_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='회사명')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='전화번호')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='이메일')),
                ('product', models.CharField(blank=True, max_length=256, null=True, verbose_name='제품')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='회사명')),
                ('budget', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망 예산')),
                ('period', models.CharField(blank=True, max_length=256, null=True, verbose_name='희망 기간')),
                ('file', models.FileField(blank=True, null=True, upload_to=App.models.request_update_filename, verbose_name='포트폴리오')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '   요청',
                'verbose_name_plural': '   요청',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager_department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to=App.models.user_portfolio_update_filename, verbose_name='포트폴리오'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '클라이언트'), (2, '파트너')], default=1, verbose_name='유저타입'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to=App.models.business_license_update_filename, verbose_name='사업자등록증'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
