# Generated by Django 2.1.7 on 2020-01-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200115_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
    ]
