# Generated by Django 2.1.7 on 2020-01-14 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_request_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='희망 예산'),
        ),
        migrations.AddField(
            model_name='project',
            name='period',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작업기간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(verbose_name='등록일자'),
        ),
    ]
