# Generated by Django 2.1.7 on 2020-01-14 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200115_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': '     요청된 의뢰', 'verbose_name_plural': '     요청된 의뢰'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='period',
        ),
        migrations.AddField(
            model_name='project',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작업종료일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작업시작일시'),
            preserve_default=False,
        ),
    ]
