# Generated by Django 2.1.7 on 2020-01-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200115_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='파트너여부'),
        ),
    ]
